INSERT INTO Problem1 VALUES('a', false, 'capaciteit levert geen unieke voertuigen');
INSERT INTO Problem1 VALUES('b', true, 'voertuig x heeft één capaciteit');
INSERT INTO Problem1 VALUES('c', true, 'zie c');
INSERT INTO Problem1 VALUES('d', true, '');
INSERT INTO Problem1 VALUES('e', true, '');
INSERT INTO Problem1 VALUES('f', false, 'als bezorger kun je meerdere voertuigen rijden');
INSERT INTO Problem1 VALUES('g', true, '');
INSERT INTO Problem1 VALUES('h', false, 'voertuig heeft maar een bezorger');
INSERT INTO Problem1 VALUES('i', false, 'voertuig heeft maar een capaciteit');
INSERT INTO Problem1 VALUES('j', false, 'voertuig heett maar een bezorger en een capaciteit');